### ISSUE TITLE
Update php-request to match

### ISSUE THREAD

**Issue by ahundiak** [pmjones/ext-request#19]
First off, kudos for trying again to get this added into the core.  I have my doubts if it will be accepted but hope springs eternal.

I would suggest updating your userland php-request project to match as closely as possible.  The idea is that it would be easier to install and test than an actual C extension.  Might help with the acceptance process.

I know that not everything can transfer easily especially immutability but as long as it is close then it would be okay.  Seeing exactly what it would take to, for example, have the Symfony Request object extend from this would be interesting.

**Comment by wiese** [comment]
> your (= pmjones's) userland php-request project

https://github.com/pmjones/php-request

**Comment by pmjones** [comment]
Done! https://github.com/pmjones/php-request/releases/tag/2.0.0
