### ISSUE TITLE
ServerResponseSender: add support for generators/iterable

### ISSUE THREAD

**Issue by llvdl** [pmjones/ext-request#20]
I noticed ServerResponseSender doesn't seem to support generators as content.

```php
$content = new class () {
    public function __invoke(): iterable
    {
        yield 'Hello ';
        yield 'world!';
    }
};

$response = new ServerResponse();
$response->setContent($content);

$sender = new ServerResponseSender();
$sender->send($response); // error: Object of class Generator could not be converted to string
```

My expectation would be no error in this case and "Hello world!" as the content. Is this a deliberate omission in the specification?

**Comment by pmjones** [comment]
Not a deliberate omission; it was not even considered. Indeed, in several years of use, this the first time such a case has been raised!

What do you think would be the "expected" mechanism for discovering that the content is a Generator (aside from reflection), and then for actually sending it?

**Comment by llvdl** [comment]
I do not have experience developing PHP extensions or PHP internals, so I can't tell you what the expected mechanism is.

There seems to be a check if the content is _callable_ in the [server_response_sender_send_content()](https://github.com/pmjones/ext-request/blob/2.x/php_request.c#L2270). 

I figured something like `Z_TYPE_P(content) == IS_ITERABLE` or `zend_is_iterable(content)` would work, but I have not had any luck in getting it to work so far.

**Comment by jbboehr** [comment]
Seems like this could be worked around like:

```php
$response->setContent(function() use ($gen) {
    $buf = '';
    foreach ($gen as $line) {
        $buf .= $line;
    }
    return $buf;
});
```

no? Although I suppose the buffer could be large so maybe not ideal.

I did find an example of an extension in core consuming an iterator [[0]]. So this would apply to generators and all iterators if it were to be implemented.

[0]: https://github.com/php/php-src/blob/afdaa91170a1f7b0387cf577d957d4d6c015c136/ext/soap/php_encoding.c#L2194-L2241

**Comment by llvdl** [comment]
Nice find! The commit works for both a function that returns an iterable as well as an invokable object that returns an iterable.
