### ISSUE TITLE
ServerResponseSender is tightly coupled to ServerResponse

### ISSUE THREAD

**Issue by jbboehr** [pmjones/ext-request#31]
Sorry this slipped my mind. I almost made a barebones user-land implementation of ServerResponseInterface for the test suite but I figured "what could possibly go wrong."

Well... ServerResponseSender sends the response by reading the properties (not using the methods) of the ServerResponse class, so ServerResponseSender needs to be refactored.

**Comment by pmjones** [comment]
WHAT COULD GO WRONG
