### ISSUE TITLE
Introduce SapiUpload class

### ISSUE THREAD

**Issue by pmjones** [pmjones/ext-request#46]
The idea would be to replace each element of SapiRequest::$uploads that uses an array descriptor, with a SapiUpload instance.

The class should look something like this:

```php
class SapiUpload
{
    public /* readonly ?string */ $name;

    public /* readonly ?string */ $name;

    public /* readonly ?int */ $size;

    public /* readonly ?string */ $tmpName;

    public /* readonly ?int */ $error;

    public function __construct(
        ?string $name,
        ?string $type,
        ?int $size,
        ?string $tmpName,
        ?int $error
    ) {
        $this->name = $name;
        $this->type = $type;
        $this->size = $size;
        $this->tmpName = $tmpName;
        $this->error = $error;
    }

    public function move(string $destination) : bool
    {
        return move_uploaded_file($this->tmpName, $destination);
    }
}
```

And SapiRequest, on building the $uploads array, should retain a new instance of SapiUpload instead of the file array descriptor.

**Comment by pmjones** [comment]
@jbboehr any thoughts on the wisdom and/or achievability of this?

**Comment by jbboehr** [comment]
Yeah, should be doable. Personally, I would say I'm generally a fan of struct-like classes over unstructured arrays.

**Comment by pmjones** [comment]
Right on. I don't remember, had we talked about this before? If so, I probably favored arrays at that point -- and have come around to your point of view on struct-like objects in this case.

**Comment by jbboehr** [comment]
I don't think we discussed this before, although I read your discussion about something similar on the mailing list.

**Comment by jbboehr** [comment]
Slight tangent: it looks like you consolidated all the classes into one file a while back, do you have anything against going back to ~one file per class? My poor little brain has trouble dealing with very large source files.

**Comment by pmjones** [comment]
I did consolidate them, to make them look more like what is in PHP core. But since it looks like adoption is low-probability at this point, splitting them back up is cool with me. Thanks for your patience with my modifications and reorganizations.
