### ISSUE TITLE
Não consigo fazer funcionar a extensão

### ISSUE THREAD

**Issue by douglas-88** [pmjones/ext-request#49]
Consegui instalar a extensão, mas quando executo : 
`$request = new SapiRequest($_POST);
  var_dump($request); `
para testar, diz que não existe essa classe.

A versão do meu PHP é a 7.2 .

![Captura de tela de 2020-04-16 10-37-03](https://user-images.githubusercontent.com/10869960/79462873-7ddf5400-7fce-11ea-8c12-7c68ed5ac0b9.png)

**Comment by pmjones** [comment]
Hi @douglas-88 --

It looks like you are installing 1.0.0b2, which called the classes `ServerRequest` instead of `SapiRequest` (etc.).

Instead, you should install version 2.0.0, which should work like this:

`pecl install request`

You will need PHP 7.3 or later.

Let me know if that helps!
